import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { AngularFireAuth } from 'angularfire2/auth';

@Component({ 
  selector: 'app-programme',
  templateUrl: './programme.page.html',
  styleUrls: ['./programme.page.scss'],
})
export class ProgrammePage implements OnInit {
  motsparjour =20;
  diapo1 : boolean;
  diapo2 : boolean;
  diapo3 : boolean;
  a=0;
  datejour= new Date();
  date1 = this.datejour.toDateString();
  dateobject = [{date : this.date1}]


  cUser = this.fAuth.auth.currentUser.uid;

  fiches;
  constructor(private httpCLient: HttpClient,public fAuth: AngularFireAuth) { }
  
  btndiapo1() {
    this.diapo1 = false;
    this.diapo2 = true;
  };
  // le lexique a push dans la base de donnée (pour la configuration)
  lexique = [
    { lvl:0, theme : 'food 1', id: 0, lexique:[
    {en:'almond' , fr:"l'amande" },
    {en:'apple' , fr: 'la pomme'},
    {en:'apple sauce' , fr:'la compote de pommes' },
    {en:'banana' , fr:'la banane' },
    {en:"banana peel" , fr:"la peau de banane" },
    {en:"batter" , fr:"la pâte" },
    {en:"bean" , fr:"le haricot" },
    {en:"beet/beetroot" , fr:"la betterave" },
    {en:"berry" , fr:"la baie" },
    {en:"black currant" , fr:"le cassis" },
    {en:"blackberry" , fr:"la mure" },
    {en:"blueberry" , fr:"la myrtille" },
    {en:"boil (to)" , fr:"faire bouillir" },
    {en:"boil an egg (to)" , fr:"faire cuire un œuf" },
    {en:"bread (to)" , fr:"paner" },
    {en:"breadcrumbs" , fr:"la chapelure" },
    {en:"breaded cutlet" , fr:"l'escalope panée" },
    {en:"bring to a boil (to)" , fr:"porter à ébullition" },
    {en:"broccoli" , fr:"le brocoli" },
    {en:"Brussels sprout" , fr:"le chou de Bruxelles" },
    {en:"bunch of bananas" , fr:"un régime de bananes" },
    {en:"bunch of grapes" , fr:"une grappe de raisin" },
    {en:"butter" , fr:"le beurre" },
    {en:"cabbage " , fr:"le chou" },
    {en:"cantaloupe melon" , fr:"le melon cantaloup" },
    {en:"carrot" , fr:"la carotte" },
    {en:"cashew" , fr:"la noix de cajou" },
    {en:"cauliflower" , fr:"le chou-fleur" },
    {en:"cherry (irregular plural: cherries)" , fr:"la cerise (les cerises)" },
    {en:"chestnut" , fr:"le marron châtaigne" },
    {en:"chickpea" , fr:"le pois chiche" },
    {en:"chili pepper " , fr:"le piment rouge" },
    {en:"chocolate chip cookie" , fr:"le biscuit aux pépites de chocolat" },
    {en:"chop (to)" , fr:"hacher" },
    {en:"chopped" , fr:"haché" },
    {en:"coconut" , fr:"la noix de coco" },
    {en:"cookie" , fr:"le petit gâteau" },
    {en:"cos lettuce" , fr:"la laitue romaine" },
    {en:"cranberry" , fr:"la canneberge airelle" },
    {en:"eggplant" , fr:"l'aubergine" },
    {en:"fried egg/egg sunny side up" , fr:"l'oeuf au plat" },
    {en:"fruit picking" , fr:"la cueillette" },
    {en:"fry (to)" , fr:"faire frire" },
    {en:"ginger" , fr:"le gingembre" },
    {en:"go nuts (to)" , fr:"devenir dingue" },
    {en:"grapefruit" , fr:"le pamplemousse" },
    {en:"grapes" , fr:"les raisins" },
    {en:"green bean" , fr:"le haricot vert" },
    {en:"green peas" , fr:"les petits pois" },
    {en:"guava" , fr:"la goyave" },
    {en:"hard-boiled egg" , fr:"l'oeuf dur" },
    {en:"hazelnut" , fr:"la noisette" },
    {en:"He/she is nuts." , fr:"Il/Elle est dingue" },
    {en:"honeydew melon" , fr:"le melon d'Espagne" },
    {en:"be in a jam (to)" , fr:"être dans le pétrin" },
    {en:"leek" , fr:"le poireau" },
    {en:"lemon" , fr:"le citron" },
    {en:"lemon peel" , fr:"le zeste de citron" },
    {en:"lettuce" , fr:"la laitue" },
    {en:"lime" , fr:"le citron vert" },
    {en:"mango" , fr:"la mangue" },
    {en:"mashed potatoes" , fr:"la purée de pommes de terre" },
    {en:"melon" , fr:"le melon" },
    {en:"mushroom" , fr:"le champignon" },
    {en:"nut/walnut" , fr:"la noix" },
    {en:"olive oil" , fr:"l'huile d'olive"},
    {en:"onion" , fr:"l'oignon"},
    {en:"organic" , fr:"biologique" },
    {en:"organic fruits and vegetables" , fr:"les fruits et légumes biologiques" },
    {en:"parsnip" , fr:"le panais" },
    {en:"passion fruit" , fr:"le fruit de la passion" },
    {en:"peach" , fr:"la pêche" },
    {en:"pear" , fr:"la poire" },
    {en:"pear jam" , fr:"la confiture de poires" },
    {en:"pecan" , fr:"la noix de pécan" },
    {en:"peel a fruit/vegetable (to)" , fr:"peler/éplucher un fruit légume" },
    {en:"pepper (red/green/yellow)" , fr:"le poivron (rouge/vert jaune)" },
    {en:"pick fruits (to)" , fr:"cueillir des fruits" },
    {en:"pineapple" , fr:"l'ananas" },
    {en:"pistachio" , fr:"la pistache" },
    {en:"pits" , fr:"les pépins/noyaux" },
    {en:"poached egg" , fr:"l'oeuf poché" },
    {en:"potato" , fr:"la pomme de terre" },
    {en:"produce" , fr:"les fruits et légumes" },
    {en:"prune" , fr:"le pruneau" },
    {en:"pumpkin" , fr:"la citrouille" },
    {en:"puree (to)" , fr:"réduire en purée" },
    {en:"raisin" , fr:"le raisin sec" },
    {en:"raspberry" , fr:"la framboise" },
    {en:"recipe" , fr:"la recette" },
    {en:"red currant" , fr:"la groseille" },
    {en:"rhubarb" , fr:"la rhubarbe" },
    {en:"rice" , fr:"le riz" },
    {en:"rind" , fr: "l'écorce/le zeste" },
    {en:"ripe" , fr:"mür" },
    {en:"sauté onions (to)" , fr:"faire sauter des oignons" },
    {en:"scrambled eggs" , fr:"les oeufs brouillés" },
    {en:"simmer (to)" , fr:"mijoter" },
    {en:"slice (to)" , fr:"couper en tranches" },
    {en:"soft-boiled egg" , fr: "l'oeuf à la coque" },
    {en:"spill the beans (to) (familiar)" , fr:"lâcher le morceau" },
    {en:"squash" , fr:"la courge" },
    {en:"squash (to)" , fr:"écraser" },
    {en:"strawberry" , fr:"la fraise" },
    {en:"string bean" , fr:"le haricot vert (fin)" },
    {en:"sweet potato/yam" , fr:"la patate douce" },
    {en:"The apple doesn't fall far from the tree." , fr:"Les chiens ne font pas des chats." },
    {en:"tomato" , fr:"la tomate" },
    {en:"turnip" , fr:"le navet" },
    {en:"walnut oil" , fr:"l'huile de noix"},
    {en:"watermelon" , fr:"la pastèque" },
    {en:"watermelon rind" , fr:"l'écorce de pastèque"},
    {en:"whip (to)" , fr:"fouetter" },
    {en:"yolk" , fr:"le jaune d'oeuf" },
    {en:"zucchini" , fr:"la courgette" },
    ] },{ lvl:0, theme : 'food 2', id: 1, lexique:[
      {en: "bay leaves", fr: "le laurier"},
      {en: "chili powder", fr: "le piment rouge en poudre"},
      {en: "cilantro/coriander", fr: "la coriandre"},
      {en: "cinnamon", fr: "la cannelle"},
      {en: "clove", fr: "le clou de girofle"},
      {en: "curry", fr: "le curry"},
      {en: "horseradish", fr: "le raifort"},
      {en: "ketchup", fr: "le ketchup"},
      {en: "mint", fr: "la menthe"},
      {en: "mustard", fr: "la moutarde"},
      {en: "nutmeg", fr: "la noix de muscade"},
      {en: "paprika", fr: "le paprika"},
      {en: "parsley", fr: "le persil"},
      {en: "pepper", fr: "le poivre"},
      {en: "rosemary", fr: "le romarin"},
      {en: "saffron", fr: "le safran"},
      {en: "sage", fr: "la sauge"},
      {en: "salt", fr: "le sel"},
      {en: "sorrel leaves", fr: "l'oseille"},
      {en: "sprinkle (to)", fr: "saupoudrer"},
      {en: "stick of cinnamon", fr: "le bâton de cannelle"},
      {en: "tarragon", fr: "l'estragon"},
      {en: "thyme", fr: "le thym"},
      {en: "vanilla", fr: "la vanille"},
      {en: "vanilla flavoring", fr: "l'arôme vanille"},
      {en: "butter", fr: "le beurre"},
      {en: "churn (to)", fr: "baratter"},
      {en: "condensed milk", fr: "le lait concentré"},
      {en: "cottage cheese", fr: "le fromage blanc"},
      {en: "cream", fr: "la crème"},
      {en: "cream cheese", fr: "le fromage frais"},
      {en: "dairy", fr: "les produits laitiers"},
      {en: "ewe cheese", fr: "le fromage de brebis"},
      {en: "fat", fr: "le gras"},
      {en: "goat cheese", fr: "le fromage de chèvre"},
      {en: "ice-cream", fr: "la glace"},
      {en: "milk a cow (to)", fr: "traire une vache"},
      {en: "skim (to)", fr: "écrémer"},
      {en: "skim (skimmed)/low-fat milk", fr: "le lait écrémé"},
      {en: "sour cream", fr: "la crème fraîche aigre"},
      {en: "spoiled milk", fr: "la crème chantilly"},
      {en: "yoghurt", fr: "le yaourt"},
      {en: "apple pie", fr: "la tarte aux pommes"},
      {en: "apple turnover", fr: "le chausson aux pommes"},
      {en: "bagel", fr: "le bagel (un petit pain rond)"},
      {en: "bake a cake (to)", fr: "faire cuire un gâteau au four"},
      {en: "baker ", fr: "le boulanger/la boulangère"},
      {en: "baker's dozen", fr: "treize à la douzaine"},
      {en: "bakery", fr: "la boulangerie"},
      {en: "batter", fr: "la pâte à gâteaux"},
      {en: "beat (to)", fr: "battre"},
      {en: "cake", fr: "le gâteau"},
      {en: "chopping board", fr: "la planche à découper"},
      {en: "danish", fr: "le pain aux raisins"},
      {en: "dough", fr: "la pâte/le pognon (mot familier)"},
      {en: "doughnut", fr: "le beignet"},
      {en: "flaky pastry", fr: "la pâte feuilletée"},
      {en: "flour", fr: "la farine"},
      {en: "fruitcake", fr: "le cake"},
      {en: "glaze (to)", fr: "glacer"},
      {en: "glazed", fr: "glacé"},
      {en: "gluten-free", fr: "sans gluten"},
      {en: "grate (to)", fr: "râper"},
      {en: "grater", fr: "la râpe"},
      {en: "have a close shave (to)", fr: "l'échapper belle"},
      {en: "It was a close shave.", fr: "Il s'en est fallu de peu"},
      {en: "key lime pie", fr: "la tarte au citron vert"},
      {en: "knead (to)", fr: "pétrir"},
      {en: "macaroon", fr: "le macaron"},
      {en: "master baker", fr: "le maître boulanger"},
      {en: "meringue", fr: "la meringue"},
      {en: "pastry", fr: "la pâtisserie"},
      {en: "pastry maker/chef", fr: "Le pâtissier / La pâtisserie"},
      {en: "pie", fr: "la tarte "},
      {en: "pie/shortcrust pastry", fr: "la pâte brisée"},
      {en: "pumpernickel", fr: "le pain noir"},
      {en: "raspberry tart", fr: "la tartelette à la framboise"},
      {en: "rise (to)", fr: "se lever"},
      {en: "rolling pin", fr: "le rouleau à pâtisserie"},
      {en: "room temperature", fr: "la température ambiante"},
      {en: "rose cream", fr: "la crème à la rose"},
      {en: "rye bread", fr: "le pain de seigle"},
      {en: "set a temperature (to)", fr: "régler la température"},
      {en: "shave chocolate (to)", fr: "raboter le chocolat"},
      {en: "sliver", fr: "une tranche fine"},
      {en: "soufflé", fr: "le soufflé"},
      {en: "stir (to)", fr: "remuer"},
      {en: "stir/fold in (to)", fr: "incorporer"},
      {en: "tart", fr: "la tartelette"},
      {en: "turnover", fr: "le chausson"},
      {en: "waffle", fr: "la gaufre"},
      {en: "whisk", fr: "le fouet de cuisine"},
      {en: "whisk away (to)", fr: "faire disparaître"},
      {en: "whisk off (to)", fr: "transporter rapidement"},
      {en: "white bread", fr: "le pain de mie"},
      {en: "yeast", fr: "la levure"},
    ] },{ lvl:0, theme : 'dining out', id: 2, lexique:[
      {en:"appetizer" , fr:"l'entrée" },
      {en:"ask for the bill/check (to)" , fr:"demander l'addition" },
      {en:"baked potato" , fr:"la pomme de terre cuite au four" },
      {en:"beef" , fr:"le boeuf" },
      {en:"beef stew" , fr:"le ragoût de boeuf" },
      {en:"bill/check" , fr:"l'addition" },
      {en:"bitter" , fr:"amer" },
      {en:"bread" , fr:"le pain" },
      {en:"breakfast" , fr:"le petit déjeuner" },
      {en:"calves liver" , fr:"le foie de veau" },
      {en:"chef" , fr:"le chef de cuisine" },
      {en:"chicken breast/fillet" , fr:"le blanc de poulet" },
      {en:"cocktail/before dinner drink" , fr:"l'apéritif" },
      {en:"coleslaw" , fr:"la salade de choux sucrée" },
      {en:"cordial/after dinner drink" , fr:"le digestif" },
      {en:"cork" , fr:"le bouchon" },
      {en:"cutlet" , fr:"l'escalope" },
      {en:"delicious" , fr:"délicieux" },
      {en:"dessert" , fr:"le dessert" },
      {en:"dine/have dinner (to)" , fr:"dîner" },
      {en:"dine out (to)" , fr:"aller au restaurant" },
      {en:"dîner" , fr:"le café-restaurant" },
      {en:"dining out" , fr:"le fait d'aller au restaurant" },
      {en:"dining room" , fr:"la salle à manger" },
      {en:"dinner" , fr:"le dîner" },
      {en:"dish" , fr:"l'assiette/le plat" },
      {en:"salad seasoning" , fr:"assaisonnement de salade (la vinaigrette)" },
      {en:"dressing fillet a fish (to)" , fr:"préparer un poisson en filets" },
      {en:"filet mignon" , fr:"le filet de boeuf" },
      {en:"fine dining" , fr:"la gastronomie" },
      {en:"finger food" , fr:"les amuse-gueules" },
      {en:"fork" , fr:"la fourchette" },
      {en:"French fries" , fr:"les frites" },
      {en:"gravy" , fr:"le jus de viande/la sauce" },
      {en:"greasy spoon" , fr:"le boui-boui" },
      {en:"ham" , fr:"le jambon" },
      {en:"have breakfast (to)" , fr:"prendre le petit déjeuner/déjeuner" },
      {en:"have lunch/luncheon (to)" , fr:"prendre le déjeuner/déjeuner" },
      {en:"hold a table (to)" , fr:"garder une table" },
      {en:"hot" , fr:"pimente/chaud" },
      {en:"hot-plate" , fr:"la plaque chauffante" },
      {en:"How many in your party?" , fr:"Vous êtes combien dans votre groupe ?" },
      {en:"knife" , fr:"le couteau" },
      {en:"lamb" , fr:"l'agneau" },
      {en:"lamb chops" , fr:"les côtelettes d'agneau" },
      {en:"leave a tip/gratuity (to)" , fr:"laisser un pourboire" },
      {en:"loaf of bread (irregular plural: loaves)" , fr:"une miche de pain (des miches)" },
      {en:"main course/entrée" , fr:"le plat principal" },
      {en:"maître d' / maître d’hôtel" , fr:"le maître d'hôtel" },
      {en:"make a reservation/book a table (to)" , fr:"faire une réservation/réserver une table" },
      {en:"meal" , fr:"le repas" },
      {en:"medium" , fr:"à point" },
      {en:"menu" , fr:"la carte" },
      {en:"napkin" , fr:"la serviette de table" },
      {en:"nibble on something (to)" , fr:"grignoter quelque chose" },
      {en:"order (to)" , fr:"commander" },
      {en:"overcooked" , fr:"trop cuit" },
      {en:"party/a party of 4" , fr:"un groupe de personnes/un groupe de 4 personnes" },
      {en:"pepper" , fr:"le poivre" },
      {en:"pork" , fr:"le porc" },
      {en:"pork chops" , fr:"les côtes de porc" },
      {en:"pork ribs" , fr:"les travers de porc" },
      {en:"rare" , fr:"saignant" },
      {en:"rib steak" , fr:"l'entrecôte" },
      {en:"roast (to)" , fr:"rôtir" },
      {en:"roast beef" , fr:"le rôti de boeuf, rosbif" },
      {en:"roll" , fr:"le petit pain" },
      {en:"run out of something (to)" , fr:"n'avoir plus de quelque chose" },
      {en:"salt" , fr:"le sel" },
      {en:"salty" , fr:"salé" },
      {en:"savory appetizer" , fr:"l'entrée salée" },
      {en:"Service is included." , fr:"Le service est compris." },
      {en:"side dish" , fr:"le plat d'accompagnement" },
      {en:"sour/tart" , fr:"acide" },
      {en:"sour cream" , fr:"la crème fraîche" },
      {en:"spices" , fr:"les épices" },
      {en:"spicy" , fr:"épicé" },
      {en:"spoon" , fr:"la cuillère" },
      {en:"spoon-feed (to) " , fr:"nourrir à la cuillère" },
      {en:"steamed" , fr:"cuit à la vapeur" },
      {en:"stew" , fr:"le ragoût" },
      {en:"succulent" , fr:"succulent" },
      {en:"supper" , fr:"le souper" },
      {en:"sweet" , fr:"doux" },
      {en:"sweetbread" , fr:"le ris de veau" },
      {en:"tablecloth" , fr:"la nappe" },
      {en:"tablespoon/soup spoon" , fr:"la cuillère à soupe" },
      {en:"tasty" , fr:"goûteux savoureux" },
      {en:"teaspoon" , fr:"la cuillère à café" },
      {en:"three-course meal" , fr:"le repas entrée/plat/dessert" },
      {en:"today's specials" , fr:"les plats du jour" },
      {en:"uncork a bottle (to)" , fr:"déboucher une bouteille" },
      {en:"undercooked" , fr:"pas assez cuit" },
      {en:"veal" , fr:"le veau" },
      {en:"veal cutlets" , fr:"les escalopes de veau" },
      {en:"very rare" , fr:"bleu" },
      {en:"wait on someone (to)" , fr:"servir quelqu'un à table" },
      {en:"waiter/Waitress" , fr:"le serveur/la serveuse" },
      {en:"warm" , fr:"tiède" },
      {en:"well-done" , fr:"bien cuit" },
      {en:"wine list" , fr:"la carte des vins" }
    ] },{ lvl:0, theme : 'finance and banking', id: 3, lexique:[
      {en:"2 grand (invariable - it cost me 2 grand)",fr:"2 mille dollars (ça m'a coûté 2 mille dollars)"},
      {en:"accrued interest",fr:"intérêt cumulé"},
      {en:"actual cost",fr:"le coût réel"},
      {en:"A.T.M. machine",fr:"un distributeur automatique de billets"},
      {en:"balance",fr:"le solde"},
      {en:"balloon (to)",fr:"augmenter rapidement"},
      {en:"bank",fr:"la banque"},
      {en:"bank check",fr:"le chèque bancaire"},
      {en:"bank on someone/something (to)",fr:"compter sur quelqu'un/quelque chose"},
      {en:"bank teller",fr:"le caissier/ la caissière"},
      {en:"banker",fr:"le banquier/la banquière"},
      {en:"banking",fr:"la profession de banquier"},
      {en:"be in debt (to)",fr:"avoir des dettes"},
      {en:"blank check",fr:"le chèque en blanc"},
      {en:"bucks (familiar)",fr:"les dollars (le surnom des dollars)"},
      {en:"carry a price tag (to)",fr:"coûter"},
      {en:"cash a check (to)",fr:"encaisser un chèque"},
      {en:"cent/penny",fr:"le cent"},
      {en:"certificate of deposit (CD)",fr:"le certificat de dépôt"},
      {en:"change",fr:"la monnaie (les pièces rendues)"},
      {en:"change (to)",fr:"faire de la monnaie"},
      {en:"check book",fr:"le carnet de chèques"},
      {en:"check stub",fr:"le talon de chèque"},
      {en:"checking/bank account",fr:"le compte en banque"},
      {en:"coin",fr:"la pièce"},
      {en:"convert (to)",fr:"convertir"},
      {en:"credit card/plastic money (familiar)",fr:"la carte de crédit"},
      {en:"creditor",fr:"le créancier/la créancière"},
      {en:"currency market",fr:"le marché des devises"},
      {en:"cut down on (to)",fr:"réduire"},
      {en:"debts",fr:"les créances"},
      {en:"deposit (to)",fr:"déposer"},
      {en:"dime",fr:"la pièce de 10 cents"},
      {en:"earn/make money (to)",fr:"gagner de l'argent"},
      {en:"economic",fr:"économique"},
      {en:"economical/thrifty",fr:"économe"},
      {en:"endorse a check (to)",fr:"endosser un chèque"},
      {en:"exchange rate",fr:"le taux de change"},
      {en:"exchange window",fr:"le guichet de change"},
      {en:"fee",fr:"la commission"},
      {en:"finance",fr:"la finance"},
      {en:"finance (to)",fr:"financer"},
      {en:"flat fee",fr:"la commission forfaitaire"},
      {en:"foreign currency",fr:"la monnaie/la devise étrangère"},
      {en:"give in to (to)",fr:"céder à"},
      {en:"go into debt (to)",fr:"s'endetter"},
      {en:"hike rates (to)",fr:"augmenter les taux"},
      {en:"I.O.U. (I owe you)",fr:"une reconnaissance de dette"},
      {en:"interest",fr:"l'intérêt"},
      {en:"interest rate",fr:"le taux d'intérêt"},
      {en:"invest (to)",fr:"investir"},
      {en:"know the odds (to)",fr:"connaître les risques"},
      {en:"lien",fr:"le gage de privilège"},
      {en:"means of payment (a means/many means)",fr:"le moyen de paiement "},
      {en:"miss an installment (to)",fr:"être en retard d'un versement"},
      {en:"monetary",fr:"monétaire"},
      {en:"money",fr:"l'argent"},
      {en:"nickel",fr:"la pièce de 5 cents"},
      {en:"offshore bank",fr:"la banque extraterritoriale"},
      {en:"open an account (to)",fr:"ouvrir un compte"},
      {en:"overdraft",fr:"le découvert"},
      {en:"overdraw an account (to)",fr:"mettre un compte à découvert"},
      {en:"paper currency",fr:"le papier-monnaie/la monnaie fiduciaire"},
      {en:"pay by check (to)",fr:"payer par chèque"},
      {en:"pay in (to)",fr:"verser"},
      {en:"pay in cash (to)",fr:"payer en espèces"},
      {en:"pay money into an account (to)",fr:"alimenter un compte"},
      {en:"payee",fr:"le / la bénéficiaire"},
      {en:"profitability",fr:"la rentabilité"},
      {en:"put a stop on a check (to)",fr:"faire opposition à un chèque"},
      {en:"put away for a rainy day (to)",fr:"mettre de l'argent de côté"},
      {en:"put up the money (to)",fr:"avancer l'argent"},
      {en:"quarter",fr:"la pièce de 25 cents"},
      {en:"raise funds (to)",fr:"se procurer des fonds"},
      {en:"ready money",fr:"l'argent disponible"},
      {en:"return on capital",fr:"la rémunération du capital"},
      {en:"safe/vault",fr:"le coffre-fort la chambre forte"},
      {en:"saving/thrift",fr:"l'économie"},
      {en:"savings account",fr:"le compte d'épargne"},
      {en:"scrimp and scrape (to)",fr:"économiser sur tout"},
      {en:"shopping binge",fr:"la frénésie d'achats"},
      {en:"spendthrift",fr:"dépensier"},
      {en:"splurge (to)",fr:"dépenser sans compter"},
      {en:"travellers checks",fr:"les chèques de voyage"},
      {en:"valuables",fr:"les objets de valeur"},
      {en:"white elephant",fr:"la réalisation coûteuse et peu rentable"},
      {en:"window",fr:"le guichet"},
      {en:"withdraw money (to)",fr:"retirer de l'argent"},
      {en:"withdrawal",fr:"le retrait"},
      {en:"write a check (to)",fr:"faire un chèque"}
    ] },{ lvl:0, theme : 'travel', id: 4, lexique:[
      {en:"airline/carrier",fr:"la compagnie aérienne le transporteur"},
      {en:"alight from/get off (to)",fr:"descendre de"},
      {en:"All aboard!",fr:"En voiture!"},
      {en:"all-inclusive",fr:"tout compris inclus"},
      {en:"anchor",fr:"l'ancre"},
      {en:"backpacker",fr:"le routard/ le randonneur /la randonneuse"},
      {en:"B. & B. (bed and breakfast)",fr:"la chambre d'hôte"},
      {en:"barge",fr:"la péniche"},
      {en:"board (to)",fr:"embarquer"},
      {en:"board a train/plane (to)",fr:"monter à bord d'un train avion"},
      {en:"boarding pass/card",fr:"la carte d'embarquement"},
      {en:"book a trip (to) ",fr:"réserver un voyage"},
      {en:"bound for (to be)",fr:"partir à destination de"},
      {en:"brake",fr:"le frein"},
      {en:"brake (to)",fr:"freiner"},
      {en:"buckle",fr:"la boucle"},
      {en:"business class",fr:"la classe affaires"},
      {en:"by train/plane/bus",fr:"en train/avion/bus"},
      {en:"caboose",fr:"le dernier wagon le fourgon de queue"},
      {en:"cancel (to)",fr:"annuler"},
      {en:"cancellation",fr:"l'annulation"},
      {en:"cater to a clientele (to)",fr:"s'adresser à une clientèle"},
      {en:"check in (to)",fr:"enregistrer (bagages...)/ S'inscrire (hôtel)"},
      {en:"check out (to)",fr:"régler sa note (d'hôtel)"},
      {en:"clutch",fr:"l'embrayage"},
      {en:"conductor",fr:"le chef de train, le contrôleur une contrôleuse"},
      {en:"connection",fr:"la correspondance (dans les transports)"},
      {en:"customs officer",fr:"le douanier"},
      {en:"dashboard",fr:"le tableau de bord"},
      {en:"delay (to)",fr:"retarder"},
      {en:"disembark (to)",fr:"débarquer"},
      {en:"dock (to)",fr:"s'amarrer"},
      {en:"fare",fr:"le prix du billet"},
      {en:"fasten one's seat belt (to)",fr:"attacher sa ceinture"},
      {en:"fleabag",fr:"l'hôtel minable"},
      {en:"flight",fr:"le vol"},
      {en:"fly (to)",fr:"voler"},
      {en:"full board",fr:"la pension complète"},
      {en:"fully booked",fr:"complet"},
      {en:"gate",fr:"la porte (à l'aéroport)"},
      {en:"get a change of scenery (to)",fr:"se changer les idées"},
      {en:"get a change of scenery (to)",fr:"se changer les idées"},
      {en:"go through customs (to)",fr:"passer les douanes"},
      {en:"guest",fr:"les client(e) d'un hotel"},
      {en:"half board",fr:"la demi-pension"},
      {en:"head for (to)",fr:"être en route pour"},
      {en:"highway",fr:"l'autoroute"},
      {en:"hold",fr:"la soute"},
      {en:"hood",fr:"le capot"},
      {en:"horn",fr:"le klaxon"},
      {en:"hull",fr:"la coque"},
      {en:"inn",fr:"l'auberge"},
      {en:"innkeeper",fr:"Aubergiste"},
      {en:"itch to go (to)",fr:"être impatient de partir"},
      {en:"jet-lag",fr:"le décalage horaire"},
      {en:"land (to)",fr:"atterrir"},
      {en:"landmark",fr:"l'attraction touristique à ne pas manquer"},
      {en:"leave for (to)",fr:"partir à"},
      {en:"long-haul flight",fr:"le vol long-courrier"},
      {en:"loosen one's seat belt (to)",fr:"desserrer sa ceinture"},
      {en:"on a plane (to be)",fr:"être dans un avion"},
      {en:"on foot",fr:"à pied"},
      {en:"on schedule (to be)",fr:"être à l'heure prévue"},
      {en:"on vacation (U.S.)/holiday (U.K.) (to be)",fr:"être en vacances"},
      {en:"one-way ticket",fr:"aller simple"},
      {en:"overbooked (to be)",fr:"être sous réserve"},
      {en:"package tour",fr:"le voyage organisé"},
      {en:"park (to)",fr:"se garer"},
      {en:"pass (to)",fr:"doubler"},
      {en:"pile-up",fr:"le carambolage"},
      {en:"platform",fr:"le quai"},
      {en:"porthole",fr:"le hublot"},
      {en:"portside",fr:"bâbord"},
      {en:"postpone (to) railroad/railway",fr:"remettre à plus tard/reporter"},
      {en:"rearview mirror",fr:""},
      {en:"(R.& R.) rest and relax ",fr:"le repos et la détente"},
      {en:"round-trip ticket",fr:"le billet aller-retour"},
      {en:"rudder",fr:"le gouvernail"},
      {en:"sail (to)",fr:"naviguer"},
      {en:"seasoned traveller",fr:"le voyageur / la voyageuse chevronné"},
      {en:"see the sights (to)",fr:"voir les hauts lieux/curiosités"},
      {en:"shift gears (to)",fr:"changer les vitesses"},
      {en:"ship",fr:"le navire"},
      {en:"sightsee (to)",fr:"faire du tourisme"},
      {en:"sightseeing/tourism",fr:"le tourisme"},
      {en:"surroundings",fr:"l'environnement"},
      {en:"spare tire",fr:"la roue/le pneu de secours"},
      {en:"starboard",fr:"tribord"},
      {en:"steering wheel",fr:"le volant le gouvernail"},
      {en:"stern",fr:"la poupe"},
      {en:"stick shift",fr:"le levier de vitesses"},
      {en:"stowaway",fr:"le passager/la passagère clandestine)"},
      {en:"strap",fr:"la sangle"},
      {en:"take a trip (to)",fr:"faire un voyage"},
      {en:"take off (to)",fr:"décoller"},
      {en:"tighten one's seat belt (to)",fr:"serrer sa ceinture"},
      {en:"tourist trap",fr:"le piège à touristes"},
      {en:"touristy",fr:"trop touristique"},
      {en:"traffic jam",fr:"l'embouteillage"},
      {en:"train car",fr:"le wagon"},
      {en:"train/bus station",fr:"la gare de chemin de fer l'autobus "},
      {en:"travel (to)",fr:"voyager"},
      {en:"travel agent",fr:"l'agent de voyage"},
      {en:"traveller",fr:"le voyageur voyageuse"},
      {en:"trip",fr:"le voyage"},
      {en:"trunk",fr:"le coffre (d'une voiture)"},
      {en:"tug boat",fr:"le remorqueur"},
      {en:"upgraded (to be)",fr:"être surclassé"},
      {en:"validate a ticket (to)",fr:"composter un billet"},
      {en:"windshield",fr:"le pare-brise"},
      {en:"windshield wiper",fr:"l'essuie-glace"},
      {en:"YMCA (Young Men's Christian Association)",fr:"l'hôtel bon marché réservé aux homme"},
      {en:"youth hostel",fr:"l'auberge de jeunesse"},
    ] },{ lvl:0, theme : 'the stock market', id: 5, lexique:[
      {en:"all-time high",fr:"le record absolu"},
      {en:"at the final bell",fr:"à la clôture"},
      {en:"bear market",fr:"le marché baissier"},
      {en:"benchmark company",fr:"la société de référence"},
      {en:"bid",fr:"une offre"},
      {en:"bid on something (to)",fr:"faire une offre d'achat"},
      {en:"blue chip stock",fr:"les actions de premier ordre"},
      {en:"bond",fr:"l'obligation"},
      {en:"bond market",fr:"le marché des obligations"},
      {en:"borrow (to)",fr:"emprunter"},
      {en:"brokerage house",fr:"la société de courtage"},
      {en:"bull market",fr:"le marché haussier"},
      {en:"buy in installments (to)",fr:"acheter en plusieurs versements"},
      {en:"call option",fr:"l'option d'achat"},
      {en:"calm fears (to)",fr:"apaiser les craintes"},
      {en:"closing price",fr:"le cours de clôture"},
      {en:"common stock",fr:"les actions ordinaires"},
      {en:"crash (to)",fr:"s'effondrer"},
      {en:"dabble in the stock market (to)",fr:"boursicoter"},
      {en:"dividend",fr:"le dividende"},
      {en:"Dow Jones industrial average",fr:"l'indice composite Dow Jones, fondé sur 30 valeurs"},
      {en:"drop in stocks",fr:"la baisse des valeur"},
      {en:"earnings per share earnings ",fr:"le bénéfice par action"},
      {en:"performance ",fr:"le rendement des actions"},
      {en:"free fall",fr:"la chute libre"},
      {en:"go broke (to)",fr:"faire faillite"},
      {en:"hedge fund manager",fr:"le gérant de fonds spéculatifs"},
      {en:"hedge funds",fr:"les fonds spéculatifs"},
      {en:"hedge your losses (to)",fr:"couvrir ses pertes"},
      {en:"high-yield",fr:"haut rendement"},
      {en:"hostile takeover",fr:"l'option publique d'achat hostile (O.P.A.)"},
      {en:"insider trading",fr:"le délit d'initié"},
      {en:"junk bond",fr:"l'obligation à haut risque (et obligation pourrie)"},
      {en:"lend (to)",fr:"prêter"},
      {en:"loan",fr:"le prêt"},
      {en:"make a killing (to)",fr:"réussir un beau coup/se remplir les poches"},
      {en:"Most Active Issues (M.A.L.)",fr:"les valeurs les plus échangées"},
      {en:"National Association of Securities Dealers Automated Quotations (N.A.S.D.A.Q.)",fr:"le système de cotation pour les valeurs hors cote"},
      {en:"New York Stock Exchange (N.Y.S.E.)",fr:"la Bourse de la ville de New York"},
      {en:"opening bell",fr:"la cloche d'ouverture"},
      {en:"opening price",fr:"le cours d'ouverture"},
      {en:"over-the-counter (O.T.C.) market",fr:"le marché hors cote"},
      {en:"penny stock",fr:"l'action très bon marché"},
      {en:"perform well/poorly (to)",fr:"bien/mal se comporter"},
      {en:"pick up steam (to)",fr:"reprendre du poil de la bête"},
      {en:"play the market (to)",fr:"jouer en Bourse"},
      {en:"price/earnings ratio (P.E.R.)",fr:"le rapport capitalisation/bénéfices"},
      {en:"public offering of shares",fr:"l'offre publique de vente (O.P.V.)"},
      {en:"public offering of shares",fr:"l'offre publique de vente (O.P.V.)"},
      {en:"pump money into the market (to)",fr:"engloutir de l'argent dans le marché"},
      {en:"put option",fr:"l'option de vente"},
      {en:"quoted on the stock market (to be)",fr:"être coté en Bourse"},
      {en:"rally (to)",fr:"remonter/se reprendre"},
      {en:"rally in",fr:"la reprise de"},
      {en:"rate",fr:"le taux"},
      {en:"rebound (to)",fr:"reprendre"},
      {en:"recoup losses (to)",fr:"récupérer ses pertes"},
      {en:"ride out the crisis (to)",fr:"surmonter la crise"},
      {en:"rig the market (to)",fr:"manipuler le marché"},
      {en:"ripple",fr:"la vague faible"},
      {en:"ruthless",fr:"sans pitié"},
      {en:"sell at a loss (to)",fr:"vendre à perte"},
      {en:"sell at a profit (to)",fr:"vendre avec un bénéfice"},
      {en:"send ripples through the market (to)",fr:"faire frémir le marché"},
      {en:"shareholder/stockholder",fr:"l'actionnaire"},
      {en:"shares of stock",fr:"les actions"},
      {en:"sharp drop",fr:"la baisse brutale"},
      {en:"shenanigans",fr:"les combines/ manigances"},
      {en:"slump",fr:"effondrement"},
      {en:"snowball effect",fr:"l'effet boule de neige"},
      {en:"spin out of control (to)",fr:"perdre le contrôle"},
      {en:"Standard & Poor's 500 (S. & P. 500)",fr:"indice de S. & P."},
      {en:"steadiness",fr:"la stabilité"},
      {en:"steady (to)",fr:"stabiliser"},
      {en:"stockbroker/trader",fr:"l'agent de change"},
      {en:"stock market/exchange",fr:"la Bourse"},
      {en:"stock market crash",fr:"le krach de la Bourse"},
      {en:"stock option",fr:"Option de souscription à des actions"},
      {en:"swing",fr:"la fluctuation"},
      {en:"take a beating (to)",fr:"prendre une raclée"},
      {en:"take a nose dive (to)",fr:"chuter brutalement"},
      {en:"target price",fr:"le prix désire"},
      {en:"tip",fr:"le tuyau"},
      {en:"tip off (to)",fr:"donner un tuyau/prévenir/avertir"},
      {en:"unchecked",fr:"incontrôlé"},
      {en:"upswing",fr:"le mouvement à la hausse"},
      {en:"volatile shares",fr:"les actions spéculatives"},
      {en:"volatility",fr:"l'instabilité"},
      {en:"wiped out (to be)",fr:"être ruiné"},
      {en:"yield",fr:"le rendement"},
      {en:"yield (to)",fr:"rapporter/céder"},
      {en:"yoyo (to)",fr:"fluctuer"},
    ] },{ lvl:0, theme : 'geography and nationalities', id: 6, lexique:[
      {en:"aftershock",fr:"la réplique (sismique)"},
      {en:"Alps (the)",fr:"les Alpes"},
      {en:"Antwerp",fr:"Anvers"},
      {en:"Arab (an)",fr:"un(e) Arabe"},
      {en:"Arabian (for a geographical region)",fr:"arabe"},
      {en:"Arabic (for the language and as an adjective)",fr:"l'arabe"},
      {en:"archipelago",fr:"l'archipel"},
      {en:"Asia",fr:"l'Asie"},
      {en:"Asian/Asiatic",fr:"asiatique"},
      {en:"Athens",fr:"Athènes"},
      {en:"Austria",fr:"l'Autriche"},
      {en:"Austrian (an)",fr:"un(e) Autrichien"},
      {en:"Bahamas (the)",fr:"les Bahamas"},
      {en:"Belgian (a)",fr:"un(e) Belge"},
      {en:"Belgium",fr:"la Belgique"},
      {en:"blend in (to)",fr:"se fondre dans"},
      {en:"Brittany",fr:"la Bretagne"},
      {en:"brook",fr:"le ruisseau"},
      {en:"Brussels",fr:"Bruxelles"},
      {en:"Bulgaria",fr:"Bulgarie"},
      {en:"Bulgarian",fr:"Bulgare"},
      {en:"Burgundy ",fr:"la Bourgogne"},
      {en:"the bush",fr:"la brousse"},
      {en:"Cairo",fr:"Le Caire"},
      {en:"Canaries (the)",fr:"les Canaries"},
      {en:"choppy waters",fr:"des eaux agitées"},
      {en:"cliff",fr:"la falaise"},
      {en:"climate",fr:"le climat"},
      {en:"Corsica",fr:"la Corse"},
      {en:"country",fr:"le pays"},
      {en:"countryside",fr:"la campagne"},
      {en:"cove",fr:"l'anse la crique"},
      {en:"Cracow",fr:"Cracovie"},
      {en:"Croatia",fr:"Croatie"},
      {en:"Croatian",fr:"Croate"},
      {en:"Cypriot",fr:"Chypriote"},
      {en:"Cyprus",fr:"Chypre"},
      {en:"Czech (a)",fr:"un(e) Tchèque"},
      {en:"Czech Republic (the)",fr:"la République tchèque"},
      {en:"Damascus",fr:"Damas"},
      {en:"Danish",fr:"un(e) Danois(e)"},
      {en:"Denmark",fr:"Danemark"},
      {en:"Dutch (the)",fr:"les Hollandais"},
      {en:"Dutchman (a)",fr:"un(e) Hollandais(e)"},
      {en:"earthquake",fr:"le tremblement de terre"},
      {en:"English (the)",fr:"les Anglais"},
      {en:"Englishman/woman (an)",fr:"un(e) Anglais(e)"},
      {en:"Estonia",fr:"Estonie"},
      {en:"Estonian",fr:"Estonien"},
      {en:"ethnic group",fr:"l'ethnie"},
      {en:"Far East (the)",fr:"l'Extrême-Orient"},
      {en:"Finland",fr:"la Finlande"},
      {en:"Finnish",fr:"un(e) Finlandais(e)"},
      {en:"Finnish",fr:"finlandais"},
      {en:"French Riviera",fr:"la Côte d'Azur"},
      {en:"freshwater",fr:"l'eau douce"},
      {en:"Geneva",fr:"Genève"},
      {en:"German (a)",fr:"un(e) Allemand(e)"},
      {en:"Germany",fr:"l'Allemagne"},
      {en:"Greece",fr:"Grèce"},
      {en:"Greek (a)",fr:"un Grec/une Grecque"},
      {en:"Greeks (the)",fr:"les Grecs"},
      {en:"Gulf of Mexico",fr:"le golfe du Mexique"},
      {en:"Havana",fr:"La Havane"},
      {en:"Hawaii",fr:"Hawaï"},
      {en:"high tide",fr:"la marée haute"},
      {en:"high seas",fr:"la haute mer"},
      {en:"hill",fr:"la colline"},
      {en:"hilly",fr:"vallonné"},
      {en:"Hungarian (a)",fr:"un(e) Hongrois(e)"},
      {en:"Hungary",fr:"la Hongrie"},
      {en:"Iceland",fr:"l'islande"},
      {en:"immigrant",fr:"l'immigré(e)"},
      {en:"immigrate (to)",fr:"immigrer"},
      {en:"indigenous people",fr:"les peuples indigènes/les autochtones"},
      {en:"inhabitant",fr:"l'habitant(e)"},
      {en:"integrate with (to)",fr:"s'intégrer à"},
      {en:"Iraq",fr:"l'Irak"},
      {en:"Iraqi (an)",fr:"un(e) Irakien(ne)"},
      {en:"Ireland",fr:"Irlande"},
      {en:"Irish",fr:"Irlandais"},
      {en:"island",fr:"L'île"},
      {en:"Israël",fr:"Israël"},
      {en:"Israeli (an)",fr:"un(e) Israélien(ne)"},
      {en:"Italy",fr:"l'Italie"},
      {en:"Italian",fr:"Italien"},
      {en: "Japan",fr:"le Japon"},
      {en:"Japanese (a)",fr:"un(e) Japonais(e)"},
      {en:"Japanese (the)",fr:"les Japonais"},
      {en:"lake",fr:"le lac"},
      {en:"landlocked",fr:"sans accès à la mer / enclavé"},
      {en:"Latvia",fr:"Lettonie"},
      {en:"Latvian",fr:"Letton"},
      {en:"lava",fr:"la lave"},
      {en:"Lithuania",fr:"Lituanie"},
      {en:"Lithuanian",fr:"Lituanien"},
      {en:"London",fr:"Londres"},
      {en:"low/ebb tide",fr:"la marée basse"},
      {en:"Luxembourg",fr:"Luxembourg"},
      {en:"Luxembourgish",fr:"Luxembourgeois"},
      {en:"mainland",fr:"la terre femelle continent"},
      {en:"Malta",fr:"Malte"},
      {en:"Maltese",fr:"Maltais"},
      {en:"Mexico",fr:"le Mexique"},
      {en:"Mexico City",fr:"Mexico"},
      {en:"Middle East (the)",fr:"le Moyen-Orient"},
      {en:"mountain range",fr:"la chaîne de montagnes"},
      {en:"native",fr:"l'autochtone"},
      {en:"Netherlands (the)",fr:"les Pays-Bas"},
      {en:"peak/top",fr:"la cime/le sommet"},
      {en:"peninsula",fr:"la péninsule"},
      {en:"Poland",fr:"Pologne"},
      {en:"Poles/Polish (the)",fr:"les Polonais"},
      {en:"Pole (a)",fr:"un(e) Polonais(e)"},
      {en:"Polish (pronounced as a closed 'o')",fr:"polonais"},
      {en:"pond",fr:"le bassin/l'étang"},
      {en:"Portugal",fr:"Portugal"},
      {en:"Portuguese",fr:"Portugais"},
      {en:"precipitous/sheer",fr:"a pic"},
      {en:"Rhine (the)",fr:"le Rhin"},
      {en:"river",fr:"le fleuve"},
      {en:"Romania",fr:"Roumanie"},
      {en:"Romanian",fr:"Roumain"},
      {en:"Rockies (the)",fr:"les (montagnes) Rocheuses"},
      {en:"saltwater",fr:"L'eau de mer"},
      {en:"Scot/Scotsman (a)",fr:"un(e) Écossais(e)"},
      {en:"Scotland",fr:"l'Ecosse"},
      {en:"Scottish",fr:"écossais"},
      {en:"seabed",fr:"le fond marin"},
      {en:"seaside",fr:"le bord de mer"},
      {en:"slope",fr:"la pente la piste"},
      {en:"Slovak",fr:"Slovaque"},
      {en:"Slovakia",fr:"Slovaquie"},
      {en:"Slovenia",fr:"Slovénie"},
      {en:"Slovenian",fr:"Slovène"},
      {en:"Spaniard (a)",fr:"un(e) Espagnol(e)"},
      {en:"Spain",fr:"Espagne"},
      {en:"Spanish (the)",fr:"les Espagnols"},
      {en:"steep",fr:"raide"},
      {en:"strait",fr:"le détroit"},
      {en:"stream",fr:"le ruisseau"},
      {en:"surf",fr:"le ressac"},
      {en:"swamp",fr:"le marais et marécage"},
      {en:"Swede (a) / Swedish",fr:"un(e) Suédois(e)"},
      {en:"Sweden",fr:"la Suède"},
      {en:"swell",fr:"la houle"},
      {en:"Swiss (a)",fr:"un(e) Suisse"},
      {en:"Switzerland",fr:"la Suisse"},
      {en:"Thaï (a)",fr:"un(e) Thaïlandais(e)"},
      {en:"Thailand",fr:"la Thaïlande"},
      {en:"The Hague",fr:"La Haye"},
      {en:"Thames (the)",fr:"la Tamise"},
      {en:"tidal wave",fr:"le raz-de-marée"},
      {en:"undertow",fr:"le courant de fond/sous-marin"},
      {en:"United Kingdom (the)",fr:"le Royaume-Uni"},
      {en:"United States (the)",fr:"les États-Unis"},
      {en:"valley",fr:"la vallée"},
      {en:"Vatican (the)",fr:"le Vatican"},
      {en:"Vienna",fr:"Vienne"},
      {en:"volcano (irregular plural: volcanoes)",fr:"le volcan (les volcans)"},
      {en:"Wales",fr:"le pays de Galles"},
      {en:"Warsaw",fr:"Varsovie"},
      {en:"waterfall",fr:"la chute d'eau"},
      {en:"Welsh",fr:"gallois"},
      {en:"Welshman/woman (a)",fr:"un(e) Gallois(e)"},
      {en:"Western world",fr:"l'Occident"},
      {en:"whirlpool",fr:"le tourbillon"},
      {en:"whitecap",fr:"le mouton"},
      {en:"wilderness",fr:"les régions sauvages"},
      {en:"xenophobic",fr:"xénophobe"},
    ] },
  ]
    
  test() {
     this.httpCLient.put( /*emplacement des fiches dans la base de donnée*/  , this.lexique)
    .subscribe(()=> {
      console.log('enregistrement terminé');
    },
      (error)=> {
        console.log('erreur de sauvegarde');
      }
      )
  }
  btndiapo2() {
    this.CopyFichesToServeur();
    this.diapo2 = false;
    this.diapo3 = true;
    this.httpCLient.put( /* push de l'objectif de l'utilisateur */ , this.motsparjour)
    .subscribe(()=> {
      console.log('enregistrement terminé');
    },
      (error)=> {
        console.log('erreur de sauvegarde');
      }
      )

      this.httpCLient.put( /*initialisation du compteur a 0*/ , this.a )
      .subscribe(()=> {
        console.log('enregistrement terminé');
      },
        (error)=> {
          console.log('erreur de sauvegarde');
        }
        )
      
      this.httpCLient.put( /*push de la date du jour*/ , this.dateobject)
      .subscribe(()=> {
          console.log('enregistrement terminé');
      },
        (error)=> {
          console.log('erreur de sauvegarde');
        }
        )


    }
  // copier toutes les fiches
  CopyFichesToServeur() {
    this.httpCLient.get<any>( /* emplacement des fiches à copier*/ )
    .subscribe ( (response) => {
      this.fiches = response;
      console.log ('copie effectuée');
      this.httpCLient.put( /*fiches de l'utilisateur */ , this.fiches)
    .subscribe(()=> {
      console.log('enregistrement terminé');
    },
      (error)=> {
        console.log('erreur de sauvegarde');
      }
      )

    },
        (error) => {
          console.log ('erreur de chargement' + error);
        }
    );
  }



  ngOnInit() {
    this.diapo1=true;
    console.log()
  }

}
